# Generated by Django 5.1.7 on 2025-03-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.JSONField(null=True),
        ),
    ]
